// <auto-generated />
using System;
using DataLib.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLib.Migrations
{
    [DbContext(typeof(DataDBContext))]
    [Migration("20201206023657_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLib.Models.Candle", b =>
                {
                    b.Property<string>("TimeFrame")
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(7)");

                    b.Property<decimal>("Close")
                        .HasColumnType("money");

                    b.Property<decimal>("Max")
                        .HasColumnType("money");

                    b.Property<decimal>("Min")
                        .HasColumnType("money");

                    b.Property<decimal>("Open")
                        .HasColumnType("money");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.Property<double>("VolumeQuote")
                        .HasColumnType("float");

                    b.HasKey("TimeFrame", "Timestamp", "Symbol");

                    b.HasAlternateKey("Symbol", "TimeFrame", "Timestamp");

                    b.ToTable("Candles");
                });
#pragma warning restore 612, 618
        }
    }
}
